version: '3.8'

services:
  vaclaims-web-frontend:
    container_name: vaclaims-web-nextjs
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: npm run dev
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - app-network
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_db_vol: