version: '3.8'

services:
  vaclaims-web-frontend:
    container_name: vaclaims-nextjs
    image: 504947529581.dkr.ecr.us-west-2.amazonaws.com/vaclaims-web-frontend:TAG_NAME
    restart: unless-stopped
    command: npm run dev
    env_file: .env
    ports:
      - "7000:3000"
    networks:
      - vaclaims-network

  portainer:
    image: portainer/portainer-ce
    container_name: portainer-frontend
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - vaclaims-network

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - "9000:8080"
  #  networks:
  #    - vaclaims-network

  #vaclaims-web-redis:
  #  image: redis:alpine
  #  ports:
  #      - "6379:6379"
  #  environment:
  #      - REDIS_PASSWORD=redis
  #  networks:
  #      - vaclaims-network

volumes:
  portainer_data:
    driver: local

networks:
  vaclaims-network:
    driver: bridge
